

version: '2'
services:
  

  specify-web-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: quay.io/mivegec/specify-web-asset-server:dev
#    restart: always
    volumes:
      - ./data/attachments:/home/specify/attachments:rw"
    ports:
      - "8080:8080"
    environment:
      - TZ=America/La_Paz
    networks:
      - default  

networks:
  default:
     driver: bridge 
